### ISSUE TITLE
iCloud3 versions < v3.0.5.3 won't work starting in HA 2024.7.2

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3_v3#309]
Adding as an FYI so hopefully some others may see this before updating. 

https://github.com/home-assistant/core/pull/121658

You may want to stay on HA 2024.7.1 until @gcobb321 gets back from vacation or you can make the changes noted [here](https://github.com/gcobb321/icloud3_v3/issues/308#issuecomment-2208242535) and also update manifest.json version to 3.0.5.3 (*at your own risk*)

manifest.json:
```yaml
{
  "domain": "icloud3",
  "name": "iCloud3 v3",
  "after_dependencies": ["recorder", "ios"],
  "codeowners": ["@gcobb321"],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://gcobb321.github.io/icloud3_v3_docs/#/",
  "iot_class": "cloud_polling",
  "issue_tracker": "https://github.com/gcobb321/icloud3_v3/issues",
  "loggers": ["icloud3"],
  "requirements": [],
  "version": "3.0.5.3"
}
```
Note that after you make this change, you may see this in your logs. You can ignore this for now.
```
homeassistant  | 2024-07-05 16:57:05.946 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State 
attributes for sensor.icloud3_event_log exceed maximum size of 16384 bytes. This can cause database performance 
issues; Attributes will not be stored
```
