### ISSUE TITLE
Possible to add "find my" alerts?

### ISSUE THREAD

**Issue by buds** [gcobb321/icloud3_v3#392]
This intergration is hands down better than the core version but sadly lacks the ability to send the "find my alerts" that core can.
These are great for alerting using HA integrations. eg Motion detected at night then send find my alert = alarm system.
Any reason icloud3 doesn't have this feature?
I could totally ditch the core versiomn if icloud3 could do these too.

**Comment by gcobb321** [comment]
I do not see iCloud3 supporting notifying the devices when a non iClou3 event occurs. It is outside the scope of iCloud3's purpose. Additionally, the Mobile App already supports a notify service that does that.

iCloud3 does support sending a  "Find my Phone" alert from the _Event Log > Actions_ drop down list. Other alert messages might be supported by the Mobile App using the many additional sensors it supports.

Here is an example of how I use the Mobile App has a `notify` service call to send a message  that  I am arriving home in about 5-minutes.

This sends the message:
```
alias: Gary - Send Message
sequence:
  - data_template:
      title: "{{ title }}"
      message: "{{ message }}"
    action: notify.mobile_app_gary_iphone_app
mode: single
icon: mdi:message-alert-outline
```

This triggers the message. See the notify scrip is in the Action item.
```
alias: Gary - 5-min Away (msg --> Gary)
description: Gary is 5-min from Home
triggers:
  - entity_id:
      - sensor.gary_iphone_travel_time
    below: 5
    trigger: numeric_state
conditions:
  - condition: state
    entity_id: sensor.gary_iphone_dir_of_travel
    state: Towards
  - condition: state
    entity_id: device_tracker.gary_iphone
    state: home
actions:
  - data_template:
      title: Gary - Close to Home Alert
      message: >-
        Est Arrival: {{  states.sensor.gary_iphone_arrival_time.state }},   {{
        states.sensor.gary_iphone_home_distance.state }}mi Away
    action: script.notify_gary_iphone
mode: single
```
Hope this helps.
